name: Build → Sign → Push to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.2.0

      - name: Build and Push Image to DockerHub
        run: |
          docker build -t saivenkatvaraprasady/n8n-node-app:latest .
          docker push saivenkatvaraprasady/n8n-node-app:latest

      - name: Get Digest from DockerHub
        id: get_digest
        run: |
          DIGEST=$(docker image inspect saivenkatvaraprasady/n8n-node-app:latest --format='{{index .RepoDigests 0}}' | cut -d "@" -f 2)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Write Cosign Key
        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key

      - name: Sign Image from DockerHub
        run: |
          cosign sign --key cosign.key --yes saivenkatvaraprasady/n8n-node-app@${{ steps.get_digest.outputs.digest }}
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

